### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation (?)

### ISSUE THREAD

**Issue by raravena80** [kubereboot/kured#609]
Hello Kured team,

I'm one of the co-chairs of the CNCF TAG-Runtime. I believe you had an agenda item to present the project in our meeting. I'm following up, I think it would be great for you to present/discuss the project in the future.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com) at your convenience. 

Thanks!

**Comment by jackfrancis** [comment]
@raravena80 will do, thanks!

cc @ckotzbauer @dholbach

**Comment by raravena80** [comment]
@jackfrancis Can you present in our next meeting Thursday? 

Thanks!

**Comment by jackfrancis** [comment]
@raravena80 thanks for circling back and following up! I just added a brief agenda line item, will be happy to demo tomorrow.

**Comment by raravena80** [comment]
@jackfrancis sweet! looking forward!

**Comment by dholbach** [comment]
This has happened already. Were there any next steps discussed?

**Comment by evrardjp** [comment]
Yeah, I am looking forward to know if we can close this, or if there are next steps :)
