### ISSUE TITLE
How to schedule Linux reboots on a specific date

### ISSUE THREAD

**Issue by Phanindra-hxgn** [kubereboot/kured#614]
Hi, 

We have  our customer environments deployed in AKS clusters. We will be performing maintenance on these environments every month.  As part of this we will be restarting the  instances in the Linux nodepools in the AKS cluster. As part of this we came to know about this KURED for Linux restarts. As we are new to this we tried to install Kured and have couple of questions, it will be helpful to us if anyone can provide some inputs for these..

I followed the instructions provided in the  [Deploy kured in an AKS cluster](https://docs.microsoft.com/en-us/azure/aks/node-updates-kured#deploy-kured-in-an-aks-cluster )

I have below questions:

- Is there a possibility to schedule the reboots on a specific date in a month ( for e.g. 20th of Every month) if so how to do that?

- I tried to execute the "helm install kured" with  rebootDays parameter at cli  to ensure that reboot should happen only only on Saturday or Sunday and Passed the parameter as  --set rebootDays="[su,sa]" but this is failing  with below error:

**Error: failed parsing --set data: key "sa]" has no value**. 
What is the correct format we should provide for a specific day at azure cli?

- If an AKS  cluster is deployed in a region ( for e.g. EastUS) and on a maintenance day if we want to restart the Linux nodes can we set the --time-zone parameter to Local i.e. --set --time-zone=Local ? so that  we can ensure that Linux reboots can  happen during our local time. 

- we have  multiple Linux node pools in our cluster - each nodepool will have 3 to 4 nodes all together there will be around 10 to 12 nodes. If we deploy kured,  whether all the nodes in a node pool will be restarted parallelly in between the given  --start-time --end-time ? 
- 
-  will KURED drain all the nodes in a nodepool one by one or will it drain parallelly? how it will ensure that there won't be any customer impact?  we want to ensure that restart process happen in parallelly. is it possible , if so how can we do that? we want to perform this with minimal impact and zero down time - is it possible?

- As I mentioned earlier , we will be performing this activity every month, so how can we edit this configuration every time. where does this configuration file resides. How to edit this configurations like Start time , end time , rebootDays,timezone etc  Please provide the command to execute at azure cli or WSL to edit the configuration.

**Comment by ckotzbauer** [comment]
Hi @Phanindra-hxgn and welcome to kured,

> Is there a possibility to schedule the reboots on a specific date in a month ( for e.g. 20th of Every month) if so how to do that

No, right now you can control the time-slots via "rebootDays", "startTime" and "endTime". There's no cron-like possibility yet. But there was another request in the past in #555 so maybe this is a valid usecase for our users and we will see this feature in the future.

> I tried to execute the "helm install kured" with rebootDays parameter at cli to ensure that reboot should happen only only on Saturday or Sunday and Passed the parameter as --set rebootDays="[su,sa]" but this is failing with below error

You have to use `--set rebootDays[0]="sa" --set rebootDays[1]="so"` or `--set rebootDays={sa, so}`
More infos: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

> If an AKS cluster is deployed in a region ( for e.g. EastUS) and on a maintenance day if we want to restart the Linux nodes can we set the --time-zone parameter to Local i.e. --set --time-zone=Local ? so that we can ensure that Linux reboots can happen during our local time.

Yes, "Local" should be a valid `time-zone` value.

> we have multiple Linux node pools in our cluster - each nodepool will have 3 to 4 nodes all together there will be around 10 to 12 nodes. If we deploy kured, whether all the nodes in a node pool will be restarted parallelly in between the given --start-time --end-time ?

Kured doesn't know about node-pools. Kured only knows the whole cluster. Nodes are never restarted in parallel. They are restarted sequentially within the given time-slot (but only if a restart for the particular node is needed).

> will KURED drain all the nodes in a nodepool one by one or will it drain parallelly? how it will ensure that there won't be any customer impact? we want to ensure that restart process happen in parallelly. is it possible , if so how can we do that? we want to perform this with minimal impact and zero down time - is it possible?

Drain is handled in the same way as the reboot, always sequentially.
1. Node is locked by kured for reboot (this only happens when no other node holds the lock)
2. Node is drained
3. Node is rebooted
4. Node is uncordoned
5. Node is unlocked

This cycle is done for all nodes which need a reboot. Drain and uncordon is done in the same way as you would do with "kubectl", so e.g. `PodDisruptionBudgets` are respected (if a PDB blocks the draining, the reboot can't be done). When you want to have minimal downtime you have to configure your workload that way, that's nothing kured does for you.

> As I mentioned earlier , we will be performing this activity every month, so how can we edit this configuration every time. where does this configuration file resides. How to edit this configurations like Start time , end time , rebootDays,timezone etc Please provide the command to execute at azure cli or WSL to edit the configuration.

You installed kured with helm, as you mentioned earlier. You have to tweak the helm-installation parameter when you want to change the kured config. The easiest way is to write your specific configs for the helm-chart down to a YAML-file (use this file as a template: https://github.com/weaveworks/kured/blob/main/charts/kured/values.yaml) and edit this file when you change the config followed by a helm upgrade:

```
helm upgrade -i kured -n kube-system kured/kured -f your-values.yaml
```

**Comment by Phanindra-hxgn** [comment]
Thank You @ckotzbauer , I will follow your suggestions and will implement it. I will update if get any issues further in this channel.

**Comment by Phanindra-hxgn** [comment]
Hi @ckotzbauer ,
I created a new values.yml file and upgraded my helm chart , I updated 
startTime: "14:00"
endTime: "17:00"
rebootDays:
  - mo
  
timeZone: Local
period: 0h1m0s
 
 and also updated the notifyUrl values.
 
 Initially there is only 1 linux Node running: ( **kubectl get nodes**) 
 
![image](https://user-images.githubusercontent.com/73598516/183404924-2976c87b-0afa-480a-8c2d-219d5d3206a9.png)

I manually created reboot-required file under /var/run folder in Linux node. Assuming that machine will be rebooted quickly  ( as the Period is set to 0h1m0s). But it was not restarting immediately ..

By the time it detected /var/run/reboot-required file .. I executed **Kubectl get pods -n kured -o wide** command 
Here are the Pods that were running during that process. It shows 2 Linux nodes aks-agentpool-16181501-vmss000008,aks-agentpool-16181501-vmss000009)
![image](https://user-images.githubusercontent.com/73598516/183405673-7e3ff46f-1958-477f-a9c6-739b2fd70224.png)

Here is the log of the pod that runs in the node aks-agentpool-16181501-vmss000008:
![image](https://user-images.githubusercontent.com/73598516/183406013-af952c6d-1ea9-4b75-9f49-a3ff8a7efb10.png)

 after reboot process , and node is uncordoned, will it delete that node create a new node ? here are the latest nodes in the cluster it is not showing the old node (aks-agentpool-16181501-vmss000008) 
 
 
![image](https://user-images.githubusercontent.com/73598516/183407148-646522ae-2894-45d9-9075-89394b1770c7.png)

Observed that it was initialing this process almost after 1 hour. I am not sure ,still why it is taking 1 hour interval to restart.  Am I doing wrong any where ?


I would also like to send  these reboot notifications to MS Teams and as per the documentation, we are supposed to pass the URL in the below format:
teams://group@tenant/altId/groupOwner?host=organization.webhook.office.com

I created a teams channel and can I user the Email address for this value ? or should I create a webhook and then copy the link of the webhook and use it here ? I am new to this terminology can you help regarding this.

 I just attached the values file which I used ( I just renamed the file to txt format to upload it here ) 
[helmvalues.txt](https://github.com/weaveworks/kured/files/9281375/helmvalues.txt)

**Comment by ckotzbauer** [comment]
I cannot clearly answer why the reboot has not happened earlier.

> after reboot process , and node is uncordoned, will it delete that node create a new node ?

No, kured doesn't add or delete nodes, that has something todo with your AKS config. The cluster seems not stable to me (as the node-count changes multiple times)

> I created a teams channel and can I user the Email address for this value ? or should I create a webhook and then copy the link of the webhook and use it here ?

You have to create a webhook.
https://containrrr.dev/shoutrrr/v0.6/services/teams/

The config looks good in general.

**Comment by ckotzbauer** [comment]
Which local timezone the hosts of your nodes are using?

**Comment by Phanindra-hxgn** [comment]
I deployed the AKS Cluster in East US region, and I am in IST time zone . So for timeZone parameter, for which I mentioned as 'Local',  will it take my IST time zone ( assuming my Linux reboots should be completed between startTime at 14:00 IST and endTime as 17:00 IST) ? or should I mention 'America/Cancun' ( for East US) , if so should we mention the startTime and endTime also  according to America/Cancum ?

as we will be performing maintenance on all these environments on a same day during our time zone (IST)  , If we have AKS Clusters deployed in different regions and when we try to reboot these Linux nodes ,  what value should we provide ?

**Comment by ckotzbauer** [comment]
The time-zone parameter always relates to the time-zone of the linux-hosts of the cluster, not to your local time-zone.
When the regions are located in different time-zones and you choose local, then your nodes will never reboot in the same time-zone.
The best thing would be to specify your local time-zone when you want to reboot the nodes relating your local time and not to the servers time-zone. "Asia/Kolkata" should be your zone.
