### ISSUE TITLE
How To Restart Multiple Nodes

### ISSUE THREAD

**Issue by TheFuzz4** [kubereboot/kured#620]
Hey there, 
Is there a method to have Kured restart multiple nodes say I want it to do X number of nodes at a time? 

Also in the event that it doesn't complete restarting all of the nodes during a time frame and then more updates are installed in the pool then it starts over from the beginning.  How can we get it to resume the rolling restart of the nodes to pick back up, where it left off from?  Thanks.

**Comment by ckotzbauer** [comment]
Hi @TheFuzz4,
this is not possible with kured. You can define the time-frame to do restarts and then kured will restart nodes which need a reboot one by one. Kured is stateless, so it doesn't know which nodes where rebooted and which not. Also there's no nodepool, groups of nodes or any other ranked node-list for kured.

What is your usecase with this?

**Comment by TheFuzz4** [comment]
Hi there @ckotzbauer so our use case is this.  Our production clusters are quite large and we currently have a limited window that we can do our reboots in over the weekend.  We also have the flag set to have it wait 10 mins between nodes to give time for the pods to settle down while they drain and move around.  Problem is even using 2 days we still don't end up with a full reboot and then the week goes by and Azure installs new updates on the nodes and then when the time window opens back up again we start back at the top of the list and now we have nodes that are no longer in sync with each other.  We have some nodes in our clusters that are now several kernel versions behind the others because they have not rebooted yet.  
This is why we would like the option to allow kured to be able to bounce multiple nodes at a time say we can tell kured you can do X number of nodes per cycle.  Or the ability to have it keep track of which nodes were rebooted last and pick back up from there instead of starting back from step 1.  Let me know if that makes sense.

**Comment by ckotzbauer** [comment]
Hm, I understand. I think something like a max-number of nodes to reboot in parallel (default 1) would be possible. But then kured has to respect zones and regions of the nodes to have a reliable process. I think its not too hard to implement, but it needs more consideration.
A state-management of which nodes where rebooted doesn't make sense to me for several reasons:
- It is never guaranteed that all nodes need a reboot. If there's only one which does not need to be rebooted (other update-settings, you rebooted it manually) then the whole cluster would not start a new reboot-cycle as the old one is not finished.
- Holding back rebooted nodes which need another reboot cause they were updated again doesn't fix the "sync problem" as then your nodes are not in sync too.
- It is beyond the simplicity which kured should focus on to make as less assumptions as possible.

**Comment by TheFuzz4** [comment]
Do you know currently what other project teams are using to handle reboots for a situation such as ours? Thank you.  If you can enable the parallel reboot that would be fantastic.

**Comment by ckotzbauer** [comment]
No, that's the first request with that topic, as far as I know.
It would be great to receive a PR for that. We, the maintainers, support with the concept, the implementation and any other question, but we don't develop things by request in general. Most of us is working on this in our free-time. 😉

**Comment by TheFuzz4** [comment]
I would love to have the knowhow to create a PR for that lol.  For now can I request the ability to be able to specify an argument to reboot X number of nodes in parallel.

**Comment by trstringer** [comment]
@TheFuzz4, does the PR #660 meet your requirements? From reading this issue, I believe it does but I'd like to verify with you!

**Comment by TheFuzz4** [comment]
Yes that is what I'm looking for. Thank you

**Comment by fishingfly** [comment]
Need to support parallel reboot

**Comment by ckotzbauer** [comment]
@fishingfly There's a linked PR without any activity from the author for longer time, feel free to help with the implementation to get this feature on the road.

**Comment by ckotzbauer** [comment]
Fixed tests and logic in linked PR.
