### ISSUE TITLE
Migrate to kubereboot/kured

### ISSUE THREAD

**Issue by dholbach** [kubereboot/kured#633]
As we are now a [CNCF Sandbox project](https://lists.cncf.io/g/cncf-toc/message/7501), we want to move to our new home `kubereboot/kured`, but we want to do it sensibly.

Items likely involved are:

- [x] ~~create a kubereboot/kured docker hub~~
- [x] ~~push our old releases there~~
- [x] Ask Weaveworks IT to transfer the repo
- [x] Make sure our Helm setup continues to work
- [x] Update instructions
- [x] ... please add ...

**Comment by evrardjp** [comment]
I was thinking about something along those lines:

1. Announce changes in github README, mentioning that there might be unavailability time of helm charts/container images
2. Migrate repo to kubereboot/kured
3. Change gh actions to push towards ghcr
4. Decide what to do with the old images: Reupload, or be clear that the legacy images are hosted on weaveworks' docker hub
5. Decide what to do with helm: Now that we have a different org, it allows us to have a different repo for helm charts, which might be easier. 
6. Reconfigure github repo with CNCF guidelines
7. Update documentation
8. Produce release to exercise gh actions behaviour.

**Comment by dholbach** [comment]
It appears that we have published everything from `1.8.2` onwards to GHCR, so that'd be support for k8s >= 1.20,

**Comment by evrardjp** [comment]
We'll check what are the fate of the ghcr images when we migrate the ownership -- if they move with the transfer of ownership, that would be quite a benefit :)

**Comment by evrardjp** [comment]
Updated post https://github.com/weaveworks/kured/issues/633#issuecomment-1250692507 with more details, and mentioning people. What I am eager to see is a view on how we'll do the helm chart going forward. If we plan to stay the same, or if we allow ourselves to have a separate repo, which might be favorable (and more clear for contributors)

**Comment by dholbach** [comment]
I was just informed that the repo move will not happen before tomorrow (Tue, 20th Sept).

**Comment by dholbach** [comment]
I just invited @morancj to be owner of the `kubereboot` org to be able to perform the repo transfer.

**Comment by dholbach** [comment]
We are still using the `weave-ghcr-bot` (as outside collaborator) to not break the build. We will have to create a new bot account I assume.

We also have `davidkarlsen` as outside collaborator - he got `triage` access a longer while ago when we worked on `kured` together. We should discuss this as part of our new governance.

**Comment by kbhalaki** [comment]
what is the new location of the chart?

**Comment by ckotzbauer** [comment]
@kbhalaki For now https://kubereboot.github.io/kured
When its moved to its own repo, it will change again (I think to https://kubereboot.github.io/charts)

**Comment by kbhalaki** [comment]
@ckotzbauer above link shows to run repo add command with broken link:

`helm repo add kured https://weaveworks.github.io/kured/`

**Comment by dholbach** [comment]
We are in the process of moving right now. It will take a little while until this is resolved.

**Comment by cesarca** [comment]
Any temporary solution? Right now this problem is affecting my work team.

**Comment by dholbach** [comment]
Images are available from GHCR https://github.com/weaveworks/kured/pkgs/container/kured

**Comment by kbhalaki** [comment]
@dholbach  Any url for the chart?

**Comment by dholbach** [comment]
We are working on bringing the chart repository back.

**Comment by dholbach** [comment]
For more context: Weaveworks kindly donated the `kured` project to the Cloud Native Computing Foundation, which accepted us as a project a week back. :tada:  This will ensure that `kured` project will live in a vendor-neutral home.

For us this is a big and exciting move. Please hang tight and be patient - we are working on this as fast as we can.

Please also join us on CNCF Slack in #kured. Contributions to the project are very welcome as well! We want our team to grow!

**Comment by kingdonb** [comment]
I noticed the issue on my prometheus dashboard (starting about 6 hours ago) and I replaced the spec.url in my HelmRepository with this one:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kured
  namespace: flux-system
spec:
  interval: 4h0m0s
  url: https://kubereboot.github.io/kured/
```

The trouble is cleared for me, if I've understood the whole thread then everything will be [moving again](https://github.com/kubereboot/kured/issues/633#issuecomment-1252109097) once more before the process is finished.

Perhaps I can help contribute something upstream so that we can publish OCI Charts next 👍 I see that we're using:

`helm/chart-releaser-action@v1.1.0` ([here](https://github.com/kubereboot/charts/blob/main/.github/workflows/release.yaml)) so if I can do anything to move along this issue, I will:

* https://github.com/helm/chart-releaser-action/issues/107

**Comment by cesarca** [comment]
> I noticed the issue on my prometheus dashboard (starting about 6 hours ago) and I replaced the spec.url in my HelmRepository with this one:
> 
> ```
> ---
> apiVersion: source.toolkit.fluxcd.io/v1beta1
> kind: HelmRepository
> metadata:
>   name: kured
>   namespace: flux-system
> spec:
>   interval: 4h0m0s
>   url: https://kubereboot.github.io/kured/
> ```
> 
> The trouble is cleared for me, if I've understood the whole thread then everything will be [moving again](https://github.com/kubereboot/kured/issues/633#issuecomment-1252109097) once more before the process is finished.
> 
> Perhaps I can help contribute something upstream so that we can publish OCI Charts next 👍 I see that we're using:
> 
> `helm/chart-releaser-action@v1.1.0` ([here](https://github.com/kubereboot/charts/blob/main/.github/workflows/release.yaml)) so if I can do anything to move along this issue, I will:
> 
> * [feat: add support for pushing charts to oci (ghcr) helm/chart-releaser-action#107](https://github.com/helm/chart-releaser-action/issues/107)
> 
> Also, 🌮 🎉 about Kured joining the CNCF!

@kingdonb use https://kubereboot.github.io/charts in spec:url

**Comment by kingdonb** [comment]
Super, confirmed I am picking up the new chart version 4.0.1 from there 👍

**Comment by cesarca** [comment]
> Super, confirmed I am picking up the new chart version 4.0.1 from there 👍

Nice 👍🏼

**Comment by evrardjp** [comment]
Side note, another version will come, with our ghcr images ;) 
Still, happy to read that 4.0.1 works.

**Comment by evrardjp** [comment]
Sorry if I didn't communicate here when the charts started to be online, I was deep into the builds.... Anyway, I hope the dust will settle now, and we can improve all together :)

**Comment by kdandersen** [comment]
> Hi, the new url: https://kubereboot.github.io/charts is operational 🎉

Hi @cesarca 

When trying to use the new Helm chart location I get the following error with a reference back to the original Weaveworks repo.

![image](https://user-images.githubusercontent.com/49781983/191445826-1ad03154-060d-450c-b05a-7dc1a0e9a6d8.png)

 I.e. I believe the index.yaml still has reference to the no longer existing Waeaveworks repo.

Kind regards
Kim

**Comment by dholbach** [comment]
Can you update to 4.0.1?

**Comment by kdandersen** [comment]
> 

A manual delete of all files the Helm Cache folder solved the issue.

Thanks
K

**Comment by mkemmerz** [comment]
As the helm chart 3.0.0 was just recently released one question. What is the difference to 4.0.x? Was this done simply for the migration or any breaking changes from v3 to v4?

**Comment by evrardjp** [comment]
The breaking change for deployers is the fact the URL has changed -- One cannot continue to use it without changing helm repos. If you check the appVersion for the helm chart, you can see it's the same. Hence, nothing has changed in kured's code itself for that breaking change.

**Comment by evrardjp** [comment]
FYI, I just edited the checklist, ticked a few boxes :)

**Comment by dholbach** [comment]
[This thread](https://lists.cncf.io/g/cncf-toc/topic/raise_50_000_for_cncf/94186234?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,94186234,previd%3D1665429870615209564,nextid%3D1654868925576067413&previd=1665429870615209564&nextid=1654868925576067413) has a bunch of security recommendations. Some might be longer term material, some might be easy to integrate.

One tool that is mentioned in there to adhere to GitHub repo best-practices is https://github.com/ossf/allstar

**Comment by dholbach** [comment]
I think we can close this now, right?

**Comment by ckotzbauer** [comment]
yes
