### ISSUE TITLE
Decide what to do with docker hub images

### ISSUE THREAD

**Issue by evrardjp** [kubereboot/kured#639]
We published our container images on dockerhub and (starting at kured version 1.8.2, I am told) also on github container registry.
They are both under weavework's management.

With the move to a different organisation, we need to take a few decisions.
1) Transfer dockerhub kured to different ownership, or not.
If we transfer, we can keep publishing images on dockerhub. We need to ask the CNCF for an organization account.
If we don't transfer, there will be old images under weaveworks's kured, and no new images in dockerhub. The new 'official home' needs to be clearly documented.
2) Upload previous images on our official ghcr. All images before 1.8.2 needs clarity.
This is especially important if we don't transfer ownership in dockerhub.
3) ReUpload images from weavework's kured ghcr into kubereboot ghcr registry, if those are not automatically transferred.

**Comment by evrardjp** [comment]
My stance on 1: I don't attach a lot of importance into the registry itself. As asking for a CNCF account my take time, I would be eager to just ignore dockerhub, and be clear that the new home of kured is only in ghcr.

My stance on 2: Do not upload images before 1.8.2 into the ghcr.

My stance on 3: Do not upload images that weren't transfered when we changed the org, if any.

**Comment by ckotzbauer** [comment]
Same for me:
1: Stop publishing to DockerHub when transferred
2: Don't upload < 1.8.2 to new ghcr.
3: Don't reupload.

**Comment by evrardjp** [comment]
Well, the previous ghcr don't come online after the transfer, so we are discussing the way forward on slack.

**Comment by evrardjp** [comment]
We have agreed (@dholbach @hiddeco and myself) to push old images (excluding the CI images) into our new ghcr repo.

**Comment by hiddeco** [comment]
All SemVer images have been copied over. If you inspect https://github.com/weaveworks/kured/pkgs/container/kured/37490432?tag=1.10.2 vs https://github.com/kubereboot/kured/pkgs/container/kured/42440576?tag=1.10.2 you can see the further SHA256 digests are the same but the statistics have been reset.
