### ISSUE TITLE
Decide what to do with helm charts

### ISSUE THREAD

**Issue by evrardjp** [kubereboot/kured#640]
The current helm charts are in the same repo as kured, which lead to questions/misexpectations of contributors in the past.
Now that we'll have a new organisation, we might want to have the official charts in that organisation in a separate repo (named charts?).

It would separate the release of those two separate artifacts, and be simpler overall.

We might want to have more than a repo anyway if we have a kubereboot/docs repo (current under discussion)...

Could you give your opinion, folks?

**Comment by ckotzbauer** [comment]
:+1: for splitting this to a separate "charts" repo

**Comment by evrardjp** [comment]
👍 for me too.

**Comment by dholbach** [comment]
→ https://github.com/kubereboot/charts

**Comment by ckotzbauer** [comment]
I'll transfer them in the next few days (during this week)

**Comment by evrardjp** [comment]
I worked on this, due to the fact that there was unavailability (the transfer of the kured repo to the new org broke the charts).
We can close this now.
