### ISSUE TITLE
Evaluate a refactor of image build

### ISSUE THREAD

**Issue by evrardjp** [kubereboot/kured#648]
As we'll need to re-evaluate our release processes, it might also make sense to think how we build the images, maybe do it a bit differently: We can now use the github actions to build container images, tag them with the right metadata (for example https://github.com/marketplace/actions/docker-metadata-action ), build them for multi-architecture (https://github.com/tonistiigi/xx ? ).

This issue should be thought about at the same time as #557 #558 #559

**Comment by ckotzbauer** [comment]
@evrardjp What exactly do you mean with this issue? With the linked issues we moved to GoReleaser which build the binaries for different platforms. For the image we use the official docker buildx GH Action now which generates multi-platform images.

What I have in mind for our build-system in the next months (maybe your thoughts are similar):
- Refactor our Action-Workflows and use reusable workflows where possible to deduplicate them.
- Cleanup and separate stuff for CI- and local builds (currently we try to achieve both with the Makefile or scripts which often doesn't work well) => I hope, that the GH Actions would be simpler then, currently they are complex and often scripted.
- Generate and sign a SLSA-Build-Provenance (I think SLSA Level 2 would be good to go)
- Upload the provenance and the SBOM (with their signatures) to the Github Release
- Evaluate another base-image (if possible) which has lower CVE potential
- Fully automate the release-build (Changelog generation, Manifests, ...)

**Comment by evrardjp** [comment]
This is _exactly_ what I was thinking :) 

Reduce mental overhead of having the different tools, just use the right tools, and make things simpler.

I would add to your list _document_ what we want to build too -> We want to avoid tribal knowledge, and make sure everyone knows how to build their own kured, and how we deliver our software for release.

**Comment by ckotzbauer** [comment]
Thanks for your feedback, I added the topic to the list.

**Comment by evrardjp** [comment]
Let's close this then.
