### ISSUE TITLE
Error: INSTALLATION FAILED: failed to download "kured/kured"

### ISSUE THREAD

**Issue by csph143** [kubereboot/kured#655]
helm repo list 
kured                                   https://kubereboot.github.io/kured                                    
p00881@Azure:~$ helm upgrade kured kubereboot/kured -n kured
Error: failed to download "kubereboot/kured"
p00881@Azure:~$ helm upgrade kured kured
Error: failed to download "kured"
p00881@Azure:~$ helm install kured kured/kured 
Error: INSTALLATION FAILED: failed to download "kured/kured"

How to install/upgrade kured now.

**Comment by ckotzbauer** [comment]
Please use the URL which is listed under https://kubereboot.github.io/kured:
The new URL is https://kubereboot.github.io/charts

**Comment by csph143** [comment]
try to delete existing one in order to install new kured, so it got struck in terminating state, any help on this.

 k get ns | grep kured
kured                       Terminating   49d

**Comment by ckotzbauer** [comment]
Maybe there's a finalizer on the namespace which blocks the deletion. You can try to edit the namespace (kubectl edit) and remove the namespace. However, it would not have been necessary to uninstall kured to change the helm repo.

**Comment by csph143** [comment]
Thanks it worked fine.
