### ISSUE TITLE
reboot-sentinel-command not working for me on EKS with Amazon Linux 2 AMI

### ISSUE THREAD

**Issue by conorboyd** [kubereboot/kured#656]
Have downloaded 1.10.2 yaml file for launching kured daemonset.
As per the current Kured documentation, I have modified the command flags to specify reboot-sentinel-command:
```
...
          command:
            - /usr/bin/kured
            - --reboot-days=tue,thu
            - --start-time=9:00
            - --end-time=16:59:59
            - --time-zone=Pacific/Auckland
            - --period=5m
            - --reboot-sentinel-command='sh -c "! needs-restarting --reboothint"'
...
```

AMI of EKS worker nodes is amazon-eks-node-1.23-v20220811

Each kured container logs the following warning:
```
level=warning msg="nsenter: can't execute 'sh -c \"! needs-restarting --reboothint\"': No such file or directory" cmd=/usr/bin/nsenter std=err
```

Among other things, I have tried added `/bin/` before `sh` and `needs-restarting`, but without success.

I can see in some other issues here that others are successfully using kured with EKS Amazon Linux 2 worker-nodes, but I can't get it to work.

Any advice please?

**Comment by evrardjp** [comment]
Can you wrap the whole thing with a script and ensure that script is present? That would be the simplest to debug. Keep in mind that you can also do differently: Organise a cron job on your nodes, which runs the script of your choice, and generates/cleans up the sentinel file.

If that works, we can then iterate on why the reboot sentinel command doesn't work for you.

**Comment by bengtfredh** [comment]
Your daemonset.apps/kured should look like this:
```
          command:
            - /usr/bin/kured
            - --reboot-days=tue,thu
            - --start-time=9:00
            - --end-time=16:59:59
            - --time-zone=Pacific/Auckland
            - --period=5m
            - --reboot-sentinel-command=sh -c "! needs-restarting --reboothint"
```
Your yaml for deploy need to look like this:
```
          command:
            - /usr/bin/kured
            - --reboot-sentinel-command=sh -c "! needs-restarting --reboothint""
```

**Comment by conorboyd** [comment]
Thanks team for the suggestions.  I've been a bit distracted with some other things recently, but I'll try and get back into this shortly and see if I can make some progress.

**Comment by conorboyd** [comment]
> Your daemonset.apps/kured should look like this:
> 
> ```
>           command:
>             - /usr/bin/kured
>             - --reboot-days=tue,thu
>             - --start-time=9:00
>             - --end-time=16:59:59
>             - --time-zone=Pacific/Auckland
>             - --period=5m
>             - --reboot-sentinel-command=sh -c "! needs-restarting --reboothint"
> ```

Thanks very much, that was it!  I got myself a bit confused with the quoting before.
