### ISSUE TITLE
Unable to install helm chart 

### ISSUE THREAD

**Issue by mack314** [kubereboot/kured#658]
Unable to install helm chart using helm v3 

helm repo add  kured https://weaveworks.github.io/kured/ -n kube-system

Error: looks like "https://weaveworks.github.io/kured/" is not a valid chart repository or cannot be reached: failed to fetch https://weaveworks.github.io/kured/index.yaml : 404 Not Found

Please advise.

**Comment by ckotzbauer** [comment]
Please use the new URL instead. https://kubereboot.github.io/charts

**Comment by WolterKamphuis** [comment]
Can you please update the url on https://artifacthub.io/packages/helm/kured/kured ?
Artifacthub points to still points to https://weaveworks.github.io/kured/

**Comment by dholbach** [comment]
Yes, that's https://github.com/kubereboot/charts/issues/5 - if you could help with that, that'd be great. My attempts have not been successful. :-/
