### ISSUE TITLE
How to manage control plan and etcd node by kured reboot daemonset 

### ISSUE THREAD

**Issue by ganeshrraorane** [kubereboot/kured#678]
We are looking for solution that after auto parch Kubernetes ubuntu node require (worker node, Etcd node and control node) automatically reboot (drain, Corden and after reboot uncorden) and it worked on worker node as expected.
But we observed that on etcd and control plan node kured solution is not worked, in fact it seems kured daemonset not manage etcd and control plan node.   

Now concern is that, Is kured solution manage etcd and control plan node as well ? If yes then how we can configure it. 

It would be great if we get guidance or help on this subject. 

Thanks 
Ganesh

**Comment by Sierra1011** [comment]
It depends on what your control plane nodes are tainted with. If you do `kubectl describe node <control plane node>`  you can see the Taints that are applied. Then you can add a Toleration to the Kured Daemonset to allow it to run on them.

For example, I am using K3s for installation, which gives me control plane nodes that look like this:
```
...
Taints:             CriticalAddonsOnly=true:NoExecute
...
```

I can use the `tolerations:` section of the deployment (I am using the Helm chart to deploy Kured) to add:
```
    tolerations:   
      - key: CriticalAddonsOnly
        operator: Exists
```

Hope this helps.

**Comment by dholbach** [comment]
Should this information be part of the faq maybe?
