### ISSUE TITLE
Document available metrics

### ISSUE THREAD

**Issue by tylerauerbeck** [kubereboot/kured#695]
Would be good to have a list of metrics that `kured` makes available documented. Currently I'm only seeing `kured_reboot_required` available and I'm unsure whether that's the only metric that `kured` exposes or if there are others that I'm just missing.

**Comment by ckotzbauer** [comment]
They are documented here: https://github.com/kubereboot/kured#prometheus-metrics
The `kured_reboot_required` metric is the only metric of kured.
Does this help?

**Comment by tylerauerbeck** [comment]
@ckotzbauer Ah, just didn't see it tucked into the README. Yepp, this is great. Only suggestion I would have is potentially splitting this out on the website as it becomes a bit more robust for easier discoverability.

**Comment by ckotzbauer** [comment]
Yes, it is planned to migrate the stuff from the readme to our new website.
