### ISSUE TITLE
Make metrics port configurable

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [kubereboot/kured#696]
Kured is [hard-coded](https://github.com/kubereboot/kured/blob/main/cmd/kured/main.go#L836) to serve metrics on port 8080. Can this be made configurable? 

There are certain cases where a port conflict could occur. For instance, we run [node-local-dns cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/), which also runs as a privileged workload and uses port 8080 to serve a health check endpoint.

**Comment by ckotzbauer** [comment]
That would be a good configuration. Do you want to open a PR for that?

**Comment by ckotzbauer** [comment]
That's a flaky test-failure and has nothing todo with the changes. Yes, one of the nodes was not rebooted or the test-mechanism has not detected the reboot correctly.

**Comment by lukemaslany-next** [comment]
I appreciate the confirmation, thanks. 👍 

Is it considered a blocker for the PR?

**Comment by ckotzbauer** [comment]
No

**Comment by ckotzbauer** [comment]
Since this is a popular feature request, I have reopened this issue. Is anyone interested in taking over the open PR #698 if @adityasundaramurthy-maersk does not finish it?
