### ISSUE TITLE
New Annotation reboot-required

### ISSUE THREAD

**Issue by timo-42** [kubereboot/kured#702]
Hi

We have some workload in the cluster, which can not be moved at will and requires maintenance windows. It would be much easier for our tools to move stuff around if Kured would set an annotation like `weave.works/kured-reboot-required=true` and we must not fall back to access an Prometheus.

`weave.works/kured-most-recent-reboot-needed` does not work for us, since it is only set when the reboot process is already started. We need an indicator beforehand, so we don't schedule long running stuff on it and move single instances in their respective maintenance window from the node.

Is this something the community would be interested in?

**Comment by jackfrancis** [comment]
not stale
