### ISSUE TITLE
Prevent cluster autoscaler from scaling down rebooted node

### ISSUE THREAD

**Issue by landerss1** [kubereboot/kured#707]
If the cluster autoscaler is quick enough to scale up when rebooting occurs, the workload from the rebooting node is moved to the new node before the rebooting process has finished, leaving the newly rebooted node unneeded. To prevent this from happening, we would need to be able to annotate the rebooting node with the following [annotation:](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node)

`"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true"`

The idea is that with this annotation, the cluster autoscaler will allow the newly rebooted node to last while it figures out that by moving the workload back to this node, the node that was scaled up can be removed instead of the rebooted one.

It would also be advisable to introduce an option to remove the annotation mentioned above after a configurable amount of time, so the cluster autoscaler can go about doing its buisness as usual again.

@jackfrancis has voluntered to do the work required for this.

**Comment by dominic-p** [comment]
I'm curious if any work has been done on this. It looks like a bot closed it due to inactivity.

I'm pretty new to Kured, but it seems like this approach could help it play nicer with CA (see #93 and [this](https://github.com/Azure/AKS/issues/1773)). Is there any documentation on how to run Kured and Cluster Autoscaler together?

**Comment by vitality411** [comment]
Still an issue. Would appreciate it if this could be reoped @jackfrancis.
