### ISSUE TITLE
Kured pods need to run without privileged permissions

### ISSUE THREAD

**Issue by selvanayaki678** [kubereboot/kured#722]
![image](https://user-images.githubusercontent.com/67256407/216540726-2b5f6e96-624a-4335-be22-2f986d3cac4e.png)
 
Facing this issue when i try to run this daemonset as a non-privilleged permission.

Please anyone from team help me on this

**Comment by ckotzbauer** [comment]
Hi @selvanayaki678,
currently it's not possible to run kured in a non-privileged mode. The reason for this is the way kured accesses the host and send reboot signals. See #416 and #526 for discussions around this topic and what would be needed to change kured in a way it doesn't need high privileges anymore.
We're happy to get feedback and help here.

**Comment by selvanayaki678** [comment]
@ckotzbauer  Thanks for the update!!

**Comment by cloud-az** [comment]
Hi. What is the status of using Kured without setting `privileged: true`?
I have checked the two issues but can not see any final conclusions.
