### ISSUE TITLE
1.12.1 release got tagged as 1.21.1

### ISSUE THREAD

**Issue by slynickel** [kubereboot/kured#726]
It looks like 1.12 release was tagged as 1.21.1 

![image](https://user-images.githubusercontent.com/26190757/217282678-089fdda6-6e71-43e5-a343-574c22e69b1f.png)

**Comment by dholbach** [comment]
Thanks for letting us know!

**Comment by slynickel** [comment]
appears it got resolved, closing.

**Comment by SNB-hz** [comment]
Could you please remove the erroneous tag 1.21.1 from Packages?
Our [automated tools](https://github.com/renovatebot/renovate) keep trying to update to 1.21.1 as it is the highest number, despite 1.12.2. being out

**Comment by dholbach** [comment]
Done, thanks for letting us know about this!
