### ISSUE TITLE
no longer needed replace line in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [kubereboot/kured#728]
It seems that `kubereboot/kured` at now indirectly depends on newer safe version `v0.5.0` of `golang.org/x/text`.
Keep following replace line in go.mod makes no sense but limits the update of `golang.org/x/text`. Should it be dropped or commented? <br>
<https://github.com/kubereboot/kured/blob/main/go.mod#L7>
```txt
replace (
    ...
    golang.org/x/text => golang.org/x/text v0.3.8
)
```
<https://github.com/kubereboot/kured/blob/main/go.mod#L90>
```txt
golang.org/x/text v0.5.0 // indirect
```

**Comment by dholbach** [comment]
Have you tried it? When I do, the older entries (which are flagged in CVE scanners) are still referred to in `go.sum`.

**Comment by Morty-luo** [comment]
Indeed, some old entries will be written to `go.sum` when dropping this line. 
```
 golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=         
 golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
 golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
 golang.org/x/text v0.3.2/go.mod h1:bEr9sfX3Q8Zfm5fL9x+3itogRgK3+ptLWKqgva+5dAk=
 golang.org/x/text v0.3.3/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
 golang.org/x/text v0.3.4/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
 golang.org/x/text v0.3.5/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
 golang.org/x/text v0.3.6/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
 golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=
 golang.org/x/text v0.4.0/go.mod h1:mrYo+phRRbMaCq/xk9113O4dZlRixOauAjOtrjsXDZ8=
 golang.org/x/text v0.5.0 h1:OLmvp0KP+FVG99Ct/qFiL/Fhk4zp4QQnZ7b2U+5piUM=
 golang.org/x/text v0.5.0/go.mod h1:mrYo+phRRbMaCq/xk9113O4dZlRixOauAjOtrjsXDZ8=
```
But entries in `go.sum` is redundant. It records every go.mod that could be reached by main module in the process of dependency analysis. <br>
For example, `k8s.io/api@v0.25.5` depends on `golang.org/x/text@v0.5.0`, while `github.com/prometheus/client_golang@v1.14.0` depends on `golang.org/x/text@v0.3.7`.
```
 golang.org/x/text v0.5.0 h1:OLmvp0KP+FVG99Ct/qFiL/Fhk4zp4QQnZ7b2U+5piUM=
```
<https://github.com/kubereboot/kured/blob/main/go.mod#L90>
```txt
golang.org/x/text v0.5.0 // indirect
```
Above line shows go finally chooses `v0.5.0` (latest version recorded in `go.sum`) of `golang.org/x/text` to build main module according to [minimal version selection](https://go.dev/ref/mod#minimal-version-selection) algorithm without effect of that replace line. <br>
`kubereboot/kured` won't depend on CVE versions of `golang.org/x/text` unless all deps depending on newer safe version of `golang.org/x/text` are dropped or downgraded, say `k8s.io/api@v0.25.5`. So, I think the risk of dropping this line is low.
