### ISSUE TITLE
[installing] Error 404

### ISSUE THREAD

**Issue by SpockIsCoding** [kubereboot/kured#740]
![image](https://user-images.githubusercontent.com/97816800/223275590-3ef14c4e-8be4-4417-b625-4937e723775e.png)

**Comment by jackfrancis** [comment]
Hi @SpockIsCoding, pasting a screenshot is not an accessible way of communicating issues. Can you kindly update the description with text?

Thank you!

**Comment by jackfrancis** [comment]
🖖
