### ISSUE TITLE
Kured upgrdation from 1.9.1 1.11.0 failed

### ISSUE THREAD

**Issue by hareeshdsinfo1** [kubereboot/kured#750]
Error: release kured failed, and has been rolled back due to atomic being set: cannot patch "kured" with kind DaemonSet: DaemonSet.apps "kured" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kured", "app.kubernetes.io/name":"kured"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by maharshirt** [comment]
https://github.com/kubereboot/charts/tree/main/charts/kured - upgrading  with helm from 2x to 3x there are few changes - you can refer that link

**Comment by hareeshdsinfo1** [comment]
Thank for the solutions.
