### ISSUE TITLE
kured segmentation fault

### ISSUE THREAD

**Issue by dgalati** [kubereboot/kured#793]
When kured  trying to "nsenter -m/proc/1/ns/mnt  -- ls -l /var/run/reboot-required" this caused a segmentation fault in the underlying host. This is ignored and evaluated as a "no reboot required".   Can this be trapped to at least indicate a failure?

**Comment by ckotzbauer** [comment]
Do you know which exit-code is returned in this case?

**Comment by dgalati** [comment]
no but i will wager that its 139

**Comment by dgalati** [comment]
Further investigation shows that the cause may be our security software
(Aquasec) causing the problem. But in any case, the kured code does not
account for exec errors. If the check for "reboot-required" fails, the code
assumes that there is no reboot required file. Therefore, needed reboots
will not happen and the problem will go undetected. It would be so helpful
if the error trapping could distinguish between "no reboot file" and an
actual error.

Code segment from main.go

func rebootRequired(sentinelCommand []string) bool {
        if err := newCommand(sentinelCommand[0],
sentinelCommand[1:]...).Run(); err != nil {
                switch err := err.(type) {
                case *exec.ExitError:
                        // We assume a non-zero exit code means 'reboot not
required', but of course
                        // the user could have misconfigured the sentinel
command or something else
                        // went wrong during its execution. In that case,
not entering a reboot loop
                        // is the right thing to do, and we are logging
stdout/stderr of the command
                        // so it should be obvious what is wrong.
                        return false
                default:
                        // Something was grossly misconfigured, such as the
command path being wrong.
                        log.Fatalf("Error invoking sentinel command: %v",
err)
                }
        }
        return true
}

**Comment by dgalati** [comment]
thank you folks for providing this error logging!

**Comment by ckotzbauer** [comment]
I think later in August, depends a bit on how fast the k8s ecosystem is moving after the 1.28.0 release tomorrow and some reviews of my co-maintainers.

**Comment by dgalati** [comment]
okay. thank you.
