### ISSUE TITLE
Kubernetes clusters should disable auto mounting API credentials 

### ISSUE THREAD

**Issue by prashant6475** [kubereboot/kured#796]
Azure Defender for cloud flags this as potential risk since it can read creds across namespaces for various services

**Comment by prashant6475** [comment]
let me know if u want me to help you out to test this @ckotzbauer  or collab ?

**Comment by ckotzbauer** [comment]
Just thought about this again, it is not possible to disable the automount for the ServiceAccount token, as kured communicates to the Kubernetes API. I'll close this issue.
