### ISSUE TITLE
Containers sharing sensitive host namespaces should be avoided

### ISSUE THREAD

**Issue by prashant6475** [kubereboot/kured#798]
We have vulnerability finding on the AKS can we have this prioritized

**Comment by ckotzbauer** [comment]
Kured does a "nsenter" operation, so the host-namespaces are needed. Right now this is a hard requirement for kured.

**Comment by prashant6475** [comment]
let me know if u want me to help you out to test this @ckotzbauer or collab ?

**Comment by ckotzbauer** [comment]
You can try to set `hostPID` on the Daemonset to false, Kured will come up, but will be unable to reboot your nodes.

**Comment by ckotzbauer** [comment]
Duplicate of https://github.com/kubereboot/charts/issues/39, I'll close this one.
