### ISSUE TITLE
Kured Helm hostNetwork problem

### ISSUE THREAD

**Issue by harrytang** [kubereboot/kured#799]
When you install Kured using Helm, the `hostNetwork` is set to true as a default setting. Consequently, this configuration renders the Kured pods incapable of resolving the Kubernetes DNS, such as `prometheus.monitoring.svc.cluster.local`.

**Comment by ckotzbauer** [comment]
I think we should set the `dnsPolicy` to "ClusterFirstWithHostNet" in the manifest and the helm-chart.

**Comment by harrytang** [comment]
I haven't experimented with the `dnsPolicy` yet. However, unless there is a specific need for `hostNetwork`, I suggest we should default its setting to false.
