### ISSUE TITLE
[Feature request] Use cloud APIs to increase node pool size before reboots and decrease after

### ISSUE THREAD

**Issue by tspearconquest** [kubereboot/kured#804]
Hi team,

We want to adopt Kured for handling our node reboots in AKS, however we have our clusters provisioned such that, as it's designed currently, Kured rebooting a node would cause our other nodes to become overloaded and run out of memory.

We would like to see the ability for Kured to make use of cloud provider APIs to increase the node pool size by one node, then decrease the node pool size after all nodes have rebooted.

This follows the pattern that cloud providers use when someone runs (for example) `az aks update --node-image-only`

**Comment by ckotzbauer** [comment]
Hi @tspearconquest,
thanks for your request. Kured's architecture is cloud agnostic, so we won't integrate with APIs of several providers.
I think it's not ideal to have a cluster sized always near on its limits. It should always be possible to loose one node without interruptions and overloadings of other nodes. Why is your cluster configured this way?

**Comment by tspearconquest** [comment]
Each node runs about between 60% to 70% memory which is optimal for non-critical workloads. With our 3 node cluster, so long as there isn't a major spike while the one node is down, the other two can handle the offloading because the workload of the one node would be divided across the other two. We configured this because it's a non-production cluster and it doesn't cause an unexpectedly large cloud bill.

```
NAME                            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
aks-d8av4-40509421-vmss000000   1186m        15%    18802Mi         67%
aks-d8av4-40509421-vmss000001   1160m        14%    17577Mi         63%
aks-d8av4-40509421-vmss000002   1579m        20%    17760Mi         64%
```

However, we also run Gitlab Runner jobs, and those can start any time someone does a git push; so if one of those jobs were to start, and then a node goes down for reboot, the remaining nodes might then become overloaded.

When we take node updates via azure cli or terraform, it creates a "surge" node and deletes that node when the reboots are finished.

**Comment by ckotzbauer** [comment]
> Each node runs about between 60% to 70% memory which is optimal for non-critical workloads. With our 3 node cluster, so long as there isn't a major spike while the one node is down, the other two can handle the offloading because the workload of the one node would be divided across the other two. We configured this because it's a non-production cluster and it doesn't cause an unexpectedly large cloud bill.


Thanks for the context. This sounds reasonable to me.
One thing you could do is, to block reboots when there are Gitlab jobs running (via Prometheus alerts). Then a reboot will only start when there are no jobs running right before draining. However, this does not prevent the start of new jobs during reboots and this would be a logic which needs to run inside the Gitlab-Build-Operator (I assue there's one :wink:), if possible.

So when this is a Dev-Cluster, I assume there are no Gitlab-Jobs in some parts of the night, maybe kured should be configured to a restricted timeframe for rebooting, this would be the safest configuration.

**Comment by tspearconquest** [comment]
> However, this does not prevent the start of new jobs during reboots 

We do make use of `requests` and `limits`, so I believe (haven't tested) the kube-scheduler won't schedule pods to a node under memory pressure; which would lead to a job being stuck in `pending` status until the memory pressure taint is removed from a node by the controller that applies it.

> So when this is a Dev-Cluster, I assume there are no Gitlab-Jobs in some parts of the night, maybe kured should be configured to a restricted timeframe for rebooting, this would be the safest configuration.

Unfortunately, no. We have jobs which take care of vulnerability scanning via a daily schedule; and the best time to do those is in the overnight hours.

**Comment by ckotzbauer** [comment]
> We do make use of requests and limits, so I believe (haven't tested) the kube-scheduler won't schedule pods to a node under memory pressure; which would lead to a job being stuck in pending status until the memory pressure taint is removed from a node by the controller that applies it.

Correct, when the pending pod can't fit the remaining requests on a node (until 100%) the scheduler won't place the pod on this node. The requests won't be exceeded (> 100%), so if they are configured well the node should not be on memory pressure. Maybe this is the best solution for your use-case.
