### ISSUE TITLE
[Bug] The new dockerhub yaml is broken, ServiceAccount is declared twice

### ISSUE THREAD

**Issue by mysticaltech** [kubereboot/kured#810]
Hello, thanks for this project. We depend on it over at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner, however your new release has a bug. 

In the do dockerhub yaml, this one https://github.com/kubereboot/kured/releases/download/1.13.2/kured-1.13.2-dockerhub.yaml, the ServiceAccount is declared twice, causing it to break kustomizations.

![ksnip_20230803-031952](https://github.com/kubereboot/kured/assets/518555/2354d193-e6e1-4a14-a1b4-6fcdfd4d0622)

Also see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/919.

**Comment by ckotzbauer** [comment]
Thanks for the report, I updated the file on the release-page. Sorry for the inconvenience.

**Comment by mysticaltech** [comment]
@ckotzbauer No worries. Thanks for the quick fix!  🙏
