### ISSUE TITLE
Unable to receive teams notification. We have the http_proxy as environment variable in kured pod

### ISSUE THREAD

**Issue by alishaik1** [kubereboot/kured#816]
2023-08-09T19:17:01Z" level=warning msg="Error notifying: an error occurred while sending notification to teams: Post <teams URL> dial tcp 40.100.47.82:443: i/o timeout"

**Comment by ckotzbauer** [comment]
Hi @alishaik1,
so `40.100.47.82` is the proxy address? Is this address (and the port) reachable from within your pod network? Can other pods reach the address?
I suspect this is no problem with Kured.

**Comment by alishaik1** [comment]
so 40.100.47.82 is the proxy address?  --- No, it is trying to ping our organisation teams url. Proxy IP is different.

Kured is working, but kured using shoutrrr module to send notification and unable to send notification if I use HTTP_PROXY. From their portal we set the http_prpxy env variable in pod. 

How does this shoutrr works in kured? How can I make use of HTTP_PROXY to send notification in kured? 
Please let us know if any test case where you are using http_proxy, triggered the reboot using kured and received the notification.

reference:
https://containrrr.dev/shoutrrr/0.7/proxy/

**Comment by ckotzbauer** [comment]
Kured just sends the notification with shoutrrr with the configured URL. There's no proxy handling or any special logic on our side.
The "HTTP_PROXY" environment variable is a golang built-in, and it seems to be used only for HTTP-Requests and the Teams-URL is HTTPS, but there's a "HTTPS_PROXY" environment variable, please try this one instead. https://pkg.go.dev/golang.org/x/net/http/httpproxy
