### ISSUE TITLE
HashiCorp license change to BSL

### ISSUE THREAD

**Issue by ckotzbauer** [kubereboot/kured#817]
This issue tracks how the Kured project might be impacted by a [HashiCorp license change](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license). For more context, see this issue for CNCF projects https://github.com/cncf/foundation/issues/617.

We use the following lib indirectly

```
github.com/hashicorp/hcl v1.0.0 // indirect
```

**Comment by dholbach** [comment]
On my phone right now, but AFAICT we pull this in through our use of spf13/viper. It might very well be listed in the license exceptions in https://github.com/cncf/foundation
