### ISSUE TITLE
Kured pods are not deployed to all nodes having taints on it in AKS ckuster

### ISSUE THREAD

**Issue by tingerbell** [kubereboot/kured#833]
I am having 2 different nodepools(system,user) taints enabled on it. Ran the below command

```
helm install test-kured1 kubereboot/kured --namespace kured  --set controller.nodeSelector."kubernetes\.io/os"=linux --set configuration.startTime=12am  --set configuration.endTime=4am  --set configuration.period=0h60m0s  --set configuration.timeZone="America/Los_Angeles"  --set configuration.rebootDays="{sun, mon,tue,wed,thu,fri,sat}" --set configuration.tolerations[0].key=node-role.kubernetes.io/agent --set configuration.tolerations[1].key=CriticalAddonsOnly --set configuration.tolerations[2].effect=NoSchedule
```

test-kured1 daemon set created without pods. Please guide me here.

**Comment by ckotzbauer** [comment]
Please use `kubectl describe daemonset test-kured1 -n kured` and have a look at the "Events" section at the bottom. There's a notice why pods can't be scheduled on particular nodes. This is a configuration issue and not an issue with kured.

**Comment by BrutalBirdie** [comment]
@tingerbell please share the taints of the nodes where kured is not being deployed to.
Also, did you reed this: https://kured.dev/docs/faq/#make-kured-run-on-control-plane-with-taint ;)
