### ISSUE TITLE
 KURED supportability of the 6.2 kernel version

### ISSUE THREAD

**Issue by chawleejay** [kubereboot/kured#836]
Our devops team has run into KURED issues with 6.2 kernel version installed on one of our nodes. We opened up a ticket with microsoft only to be told that this issue would need to be resolved with the kured team.

We run our kured process every sunday to check for patches and the last 2 sundays we've run into issues (pods not spinning up) due to a bug on kernel version 6.2

**Comment by ckotzbauer** [comment]
Hi @chawleejay,
we need a bit more infos please :wink:
- Which kured version do you use?
- Which configuration you are using?
- Which OS your nodes are running on?
- Please do a `kubectl describe` of the kured daemonset right after installing kured and post the output here

Thanks
