### ISSUE TITLE
kured cordon node before checking if just 1 up

### ISSUE THREAD

**Issue by davhdavh** [kubereboot/kured#841]
If a reboot is required, kured will cordon the node before it obtains the concurrency lock.

ie. if you currently just have a single control-plane running due to some other problem, and the auto updater kicks in marking the node reboot-required kured will gladly cordon the last control-plane and leave the cluster in a state where nothing happens.

**Comment by davhdavh** [comment]
waiting for someone to take a look

**Comment by jackfrancis** [comment]
Hi @davhdavh, I'm not seeing what your report in the way the code is implemented. We _do_ set a "prefer do not schedule" taint, if configured, immediately upon detecting that a reboot is required, but we don't actually cordon/drain until the lock is acquired. Ref:

- https://github.com/kubereboot/kured/blob/1.14.2/cmd/kured/main.go#L778-L782

Which version of kured are you using?

**Comment by davhdavh** [comment]
1.14.1
This is what happens:
`kubectl describe node xxx`
![image](https://github.com/kubereboot/kured/assets/1201165/bcf57fe3-0d15-427c-bbbd-a36f75386ebf)
Logs from kured:
![image](https://github.com/kubereboot/kured/assets/1201165/2b9c977d-80fb-45f2-be6e-49d537c2d8b0)
![image](https://github.com/kubereboot/kured/assets/1201165/3d21c27b-c2a5-42ba-8e63-ec5ca44111f5)

So it is getting the lock (because there is only 1 master, so nothing else could be holding it), but it cannot complete the reboot, so it gets stuck in situation where the cluster just dies.

**Comment by ckotzbauer** [comment]
Hi @davhdavh,
the log already shows the reason for the behaviour. There are PDBs in your cluster which prevent pods from being evicted. Kured only makes sense when the cluster can be rebooted automatically. This is not the case, as every drain - automated through kured or manual via kubectl - will fail. This is nothing kured can handle.
