### ISSUE TITLE
Is there any plan to release Kured 1.15.0 image to docker.io or ghcr.io? 

### ISSUE THREAD

**Issue by bhupendra-vaishnav** [kubereboot/kured#911]
Is there any plan to release Kured 1.15.0 image to [docker.io](https://hub.docker.com/r/weaveworks/kured/tags) or [ghcr.io](https://github.com/weaveworks/kured/pkgs/container/kured)? 

If its already released then please share location to download.

**Comment by ckotzbauer** [comment]
Hi @bhupendra-vaishnav,
we stopped our docker.io pushes a few releases ago. The push or images to `ghcr.io/kubereboot/kured`, we switched our org-name about two years ago.

**Comment by bhupendra-vaishnav** [comment]
Is there any plan to release Kured 1.15.0 image? 
After org-name change, where you are maintaining Kured container images?

**Comment by ckotzbauer** [comment]
https://github.com/kubereboot/kured/pkgs/container/kured
