### ISSUE TITLE
[Suggestion] - Change default reboot path to something else

### ISSUE THREAD

**Issue by GitFromTheInternet** [kubereboot/kured#934]
When doing OS updates on Debian systems, if a reboot is required, Debian creates a file at the exact same path: /var/run/reboot-required

Installing this on a system with that file already in place could lead to unwanted reboots.

**Comment by ckotzbauer** [comment]
Hi @GitFromTheInternet,
it is absolutely intended, that this is the default. As this file is used for many operating-systems, the users do not need to modify the settings of kured. Controllers with such an impact to a whole system like Kured should never be installed without knowing exactly what you're doing and how the current state of your machines is.
Kured should never be installed on a system with settings that are not capable for the environment. E.g. when it is only allowed to reboot the machines on weekends, then the settings need to be modified before kured is installed. Also a testing-phase on a development cluster is advisable.
