### ISSUE TITLE
kured version 5.4.1 disregard rebootsentinel flag on installation

### ISSUE THREAD

**Issue by Marnus-spec** [kubereboot/kured#949]
From kured version 5.4.1 the reboot sentinel flags are begin ignored on installation. When doing helm get values on kubereboot values are there but ignored in the daemonset.

reboot-sentinel set to /sentinel/reboot-required but in the values.yaml file set to /var/run/reboot-required
reboot-sentinel-command ignored but in values.yaml file set to sh -c "! needs-restarting --reboothint"

USER-SUPPLIED VALUES:
configuration:
  annotateNodes: true
  concurrency: "1"
  drainGracePeriod: "-1"
  drainTimeout: "0"
  endTime: "16:00"
  forceReboot: false
  lockReleaseDelay: 0
  logFormat: text
  messageTemplateDrain: Draining node %s
  messageTemplateReboot: Rebooting node %s
  messageTemplateUncordon: Node %s rebooted & uncordoned successfully!
  period: 5m
  preferNoScheduleTaint: weave.works/kured-node-reboot
  rebootCommand: /bin/systemctl reboot
  rebootDays:
  - su
  - mo
  - tu
  - we
  - th
  - fr
  - sa
  rebootDelay: 90s
  **rebootSentinel: /var/run/reboot-required**
  **rebootSentinelCommand: sh -c "! needs-restarting --reboothint"**
  skipWaitForDeleteTimeout: "60"
  startTime: "03:00"
  timeZone: Africa/Johannesburg
tolerations:
- operator: Exists

Daemonset configuration:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kubereboot
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kured
        helm.sh/chart: kured-5.4.1
    spec:
      containers:
      - args:
        - --ds-name=kubereboot-kured
        - --ds-namespace=kube-system
        - --metrics-port=8080
        - --end-time=16:00
        - --period=5m
        - --drain-grace-period=-1
        - --drain-timeout=0
        - --skip-wait-for-delete-timeout=60
        - --reboot-days=su
        - --reboot-days=mo
        - --reboot-days=tu
        - --reboot-days=we
        - --reboot-days=th
        - --reboot-days=fr
        - --reboot-days=sa
        - --reboot-sentinel=/sentinel/reboot-required
        - --reboot-command=/bin/systemctl reboot
        - --reboot-delay=90s
        - --message-template-drain=Draining node %s
        - --message-template-reboot=Rebooting node %s
        - --message-template-uncordon=Node %s rebooted & uncordoned successfully!
        - --start-time=03:00
        - --time-zone=Africa/Johannesburg
        - --annotate-nodes=true
        - --prefer-no-schedule-taint=weave.works/kured-node-reboot
        - --log-format=text
        - --concurrency=1

**Comment by ckotzbauer** [comment]
Hi @Marnus-spec,
please set `.configuration.useRebootSentinelHostPath` to `false` in the user-values.

**Comment by Marnus-spec** [comment]
Hi @ckotzbauer , thank you very much.
Adding value helped
