### ISSUE TITLE
Feature Request: Pre and Post restart API call

### ISSUE THREAD

**Issue by Sparkz0629** [kubereboot/kured#957]
Hi Team, 

I work as part of a team in a corporate setting.

One of the requirements for us to do server reboots is to get a change request number before hand, and close the change request after the fact.

This can all be done via API.

Is there a possibility for a "pre" and "post" api call on the restart process?
If the request for a change number fails, then the reboot should not go ahead.

Thanks

**Comment by ckotzbauer** [comment]
Hi @Sparkz0629,
maybe it would be possible to add a generic pre- and post-action where the user can do whatever he likes. However, this shouldn't be a blocking factor in my opinion.

**Comment by Sparkz0629** [comment]
> Hi @Sparkz0629, maybe it would be possible to add a generic pre- and post-action where the user can do whatever he likes. However, this shouldn't be a blocking factor in my opinion.

Yeah that would make sense to have a "do whatever" pre and post. Although, the blocking requirement should be configurable from my perspective. That way we can toggle if required (Defaulted to non-blocking). Thoughts?

**Comment by ckotzbauer** [comment]
The blocking requirement would increase complexity a lot and would make debugging (why the node does not reboot) even harder. I'm personally no fan of this.
