### ISSUE TITLE
Allow tainting Nodes even when blocker Pods exist

### ISSUE THREAD

**Issue by yaraskm** [kubereboot/kured#970]
I'm proposing an optimization that should help a cluster perform a full reboot faster when there are blocker conditions.

Currently, the [logic is as follows](https://github.com/kubereboot/kured/blob/main/cmd/kured/main.go#L764-L775) when using both `--blocking-pod-selector` and `--prefer-no-schedule-taint` :

```go
var rebootRequiredBlockCondition string
if rebootBlocked(blockCheckers...) {
	rebootRequiredBlockCondition = ", but blocked at this time"
	continue
}
log.Infof("Reboot required%s", rebootRequiredBlockCondition)

if !holding(lock, &nodeMeta, concurrency > 1) && !acquire(lock, &nodeMeta, TTL, concurrency) {
	// Prefer to not schedule pods onto this node to avoid draing the same pod multiple times.
	preferNoScheduleTaint.Enable()
	continue
}
```

By this point, we know that the Node requires a reboot, but if a blocker exists (e.g. Prometheus alert is firing or Pods exist on the node that match the blocking selector), the main loop will just go back to sleep and wait for the next tick without tainting the node. The problem here though is that more blocker Pods could be scheduled to this node while we wait for the next tick cycle to happen, meaning that it could take an extensively long period before the Node happens to be free of blocker Pods and can be rebooted.

My proposal is to add a flag so that Nodes will be tainted as `PreferNoSchedule` as soon as they're detected as requiring a reboot, then the block checker can continue as normal. This way, there is a high chance that blocker Pods will schedule on other nodes instead, as long as the scheduler can accommodate them somewhere else. Once all of the blocking conditions have cleared, the Node will reboot as normal.

I'm happy to submit a PR to create this flag if it's agreed to!

**Comment by ckotzbauer** [comment]
Hi @yaraskm,
there's already a `prefer-no-schedule-taint` flag for kured which does exactly what you describe.

**Comment by yaraskm** [comment]
Hi @ckotzbauer ,

I don't think this should be closed. I'm using the flag `--prefer-no-schedule-taint` as you mentioned. I was trying to raise the point that if you use `--prefer-no-schedule-taint` and `--blocking-pod-selector` and some condition blocks the reboot, the nodes will not get tainted.

What I'm proposing is either:
- Change the default behaviour so that nodes always get tainted, regardless of whether there exist reboot blockers or not
- Add a new flag so the taint is applied regardless of blocking conditions

**Comment by yaraskm** [comment]
I've created a draft PR for the behaviour change I'm suggesting: #971

**Comment by yaraskm** [comment]
I've been running my PR in our clusters for the past week and it's working as planned. Now, nodes get tainted when they need a reboot, regardless of whether there are blocking Pods or not.

**Comment by Jarusk** [comment]
I've created a PR to revive this feature and am happy to adapt it if needed. As others mentioned in the [previous PR review](https://github.com/kubereboot/kured/pull/971#issuecomment-2558585806), this will allow a full cluster reboot to progress more quickly when ephemeral workloads, like Jenkins builds, are being dispatched to the cluster and blocking reboots via pod selector.

**Comment by evrardjp** [comment]
If it's for speed, kured v2 will react quite faster. I don't think it's worth reopening this.

At the end it's opinions. Some ppl will want to taint, some other won't.
In kured v2 case, you will have a _condition_ showing the inhibition applied on the node. 
The taint will be applied based on the _desired state_ of the reboot. If you want to reboot, then it's gonna be tainted. If you don't want (like you have recently rebooted), then the taint is removed.
I belive this is far cleaner and far more explicit. I think it is easier to reason about it.

In v2, while everything goes super fast, you can ALSO HAVE YOUR OWN CONTROLLER setting the conditions you want. You want your own logic? Doable :) 

I think it's enough for us to close this issue.
