### ISSUE TITLE
Vulnerability Name: Alpine Linux 3.20 Security Update for Open Secure Sockets Layer (OpenSSL)

### ISSUE THREAD

**Issue by Abhishek199910** [kubereboot/kured#986]
Hi everyone,

Are there any plans to address below vulnerability, our scanner detected a few vulnerabilities that have been addressed in the latest Alpine Linux version for OpenSSL.

"VulnId": 514077,
"VulnerabilityName": Alpine Linux 3.20 Security Update for Open Secure Sockets Layer (OpenSSL),

Best regards

**Comment by evrardjp** [comment]
We are working on a new release at the moment. Please double check our security policy too.
